plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    // RRV
    implementation("cc.cassian.rrv:reliable-recipe-viewer-fabric:${rrv_version}")

    // JEI
    compileOnly "mezz.jei:jei-1.21.11-neoforge:${jei_version}"

    // Reliable Recipes
//    modImplementation "maven.modrinth:reliable-recipes:${reliable_recipes_fabric_version}"
//    include "maven.modrinth:reliable-recipes:${reliable_recipes_fabric_version}"

    // Cloth Config
    compileOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
    implementation "com.terraformersmc:modmenu:${mod_menu_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}

sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}

publishMods {
    file = tasks.named("jar").flatMap { it.archiveFile }
}