org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.caching.debug=false
fabric.loom.dropNonIntermediateRootMethods=true

# Mod properties
mod.version=3.2.1
mod.group=com.evandev.reliable_remover
mod.id=reliable_remover
mod.name=Reliable Remover
mod.author=Evan
mod.credits=
mod.description=A lightweight utility for completely removing items via simple JSON configuration.
mod.license=MIT
publish.modrinth=pLxsKvNt
publish.curseforge=1420447

# Mod setup
deps.fabric_loader=0.19.5
deps.neoforge_loader_version_range=[4,)
deps.java_version=25
deps.mixin_constraints=1.1.0
loomx.loom_version=1.17-SNAPSHOT