mod.mc_dep_fabric=~1.20.1
deps.minecraft=1.20.1

deps.java_version=17
deps.fabric_loader=0.18.0
deps.fabric_api=0.92.2+1.20.1
deps.modmenu=7.2.2
deps.yacl=3.6.6+1.20.1-fabric
deps.reliable_recipes=3.3.0+1.20.1
deps.emi=1.1.24+1.20.1
deps.jei=15.20.0.127
deps.jeed=kRjsKEYr
deps.emi_loot=0.7.9+1.20.1+fabric
