plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id "com.matthewprenger.cursegradle" version "1.4.0"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"
    validateAccessTransformers = true

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = at
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    compileOnly 'org.jetbrains:annotations:26.0.2-1'

    // EMI
    modImplementation "dev.emi:emi-forge:${emi_version}"

    // JEI
    modImplementation "mezz.jei:jei-${minecraft_version}-forge:${jei_version}"

    // Cloth Config
    modImplementation "me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}"

    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5:processor")
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}

curseforge {
    apiKey = System.getenv("CURSEFORGE_TOKEN") ?: "0"
    project {
        id = "1420447"
        releaseType = "release"
        changelog = file('../CHANGELOG.md')
        changelogType = 'markdown'

        addGameVersion "1.20.1"
        addGameVersion "Java 17"
        addGameVersion "Forge"

        mainArtifact(jar) {
            displayName = "Reliable Remover Forge ${project.minecraft_version} - ${project.version}"
        }

        relations {
            optionalDependency "reliable-recipes"
            optionalDependency "emi"
            optionalDependency "jei"
            optionalDependency "cloth-config"
        }
    }
}

tasks.named('curseforge') {
    dependsOn tasks.named('reobfJar')
}