mod.mc_dep_forgelike=[1.20.1,1.20.2)
deps.minecraft=1.20.1

deps.java_version=17
deps.parchment=2023.09.03
deps.forge=47.4.10
deps.yacl=3.6.6+1.20.1-forge
deps.reliable_recipes=3.4.1+1.20.1
deps.emi=1.1.24+1.20.1
deps.jei=15.20.0.127
deps.cnm=2.0.7+1.20.1-forge
deps.jeed=6zbEptBe
deps.emi_loot=0.7.9+1.20.1+forge
